Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,14 +2,59 @@ name: Automated EC2 Deployment
 
 on:
   push:
-    branches: [ main ]
+    branches:
+      - main
 
 jobs:
-  deploy:
+
+  build-and-validate:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+
+      # Terraform validation
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+
+      - name: Terraform Init
+        working-directory: ./terraform
+        run: terraform init -backend=false
+
+      - name: Terraform Validate
+        working-directory: ./terraform
+        run: terraform validate
+
+      - name: Terraform Format Check
+        working-directory: ./terraform
+        run: terraform fmt -check
+
+      # Install Ansible
+      - name: Install Ansible
+        run: |
+          sudo apt update
+          sudo apt install -y ansible
+
+      - name: Ansible Syntax Check
+        run: ansible-playbook ansible/playbook.yml --syntax-check
+
+      # Dockerfile check
+      - name: Validate Dockerfile
+        run: |
+          if [ -f app/Dockerfile ]; then
+            echo "Dockerfile exists"
+          else
+            echo "Dockerfile missing"
+            exit 1
+          fi
+
+  deploy:
+    needs: build-and-validate
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout Repository
         uses: actions/checkout@v3
 
       - name: Setup SSH
